import yeelight
import socket
import struct
import time
import subprocess
from yeelightLib import *
logger = getLogger()


USE_MONITOR_ADVERT_BULBS = True
USE_MONITOR_BULB_STATIC = False
USE_MONITOR_BULB_PING = True

SLEEP_TIME = 240


def monitor_advert_bulbs(event, cond):
    """
    Monitors Yeelights default multicast host and port
    Yeelight bulbs will advertise their presence on startup and every 60 minutes afterwards
    :param pipe:
    :return:
    """
    setprocname('Advert bulbs')
    
    # Default yeelight multicast group and port
    MCAST_GRP = '239.255.255.250'
    MCAST_PORT = 1982
    
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    # on this port, receives ALL multicast groups
    sock.bind(('', MCAST_PORT))
    
    mreq = struct.pack("4sl", socket.inet_aton(MCAST_GRP), socket.INADDR_ANY)
    
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)
    
    while True:
        try:
            res = sock.recv(10240)
            # ssdp:discover is generated by our own discovery probes and should not
            # trigger another rebuild. Only Yeelight notifications should wake the server.
            is_yeelight_advert = b'yeelight://' in res and b'model:' in res
            if b'ssdp:discover' not in res and is_yeelight_advert:
                event.set()
                with cond:
                    logger.info("Advertising bulb wake")
                    cond.notify()
        except:
            logger.exception('Got exception in advert bulb!')

def monitor_bulb_static(event, cond):
    """
    Monitors for bulb connection/disconnections. Mainly for disconnections.
    :param event:
    :return:
    """
    setprocname('Static bulbs')
    current_bulbs_ips = sorted(set(bulb['ip'] for bulb in yeelight.discover_bulbs() if bulb['ip'] in BULB_IPS))
    
    while True:
        try:
            found_bulbs_ip = sorted(set(bulb['ip'] for bulb in yeelight.discover_bulbs(1) if bulb['ip'] in BULB_IPS))
            if current_bulbs_ips != found_bulbs_ip:
                # Retry 3 times. Sometimes a bulb doesn't respond for whatever reason.
                for _ in range(3):
                    tmp_found_bulbs_ip = sorted(set(bulb['ip'] for bulb in yeelight.discover_bulbs(0.8) if bulb['ip'] in BULB_IPS))
                    if tmp_found_bulbs_ip == current_bulbs_ips:
                        break
                else:
                    new_ips = set(found_bulbs_ip) - set(current_bulbs_ips)
                    missing_ips = set(current_bulbs_ips) - set(found_bulbs_ip)
                    for new_ip in new_ips:
                        logger.info('Found new bulb at ip addr: %s', new_ip)
                    for missing_ip in missing_ips:
                        logger.info('Missing bulb at ip addr: %s', missing_ip)
                    
                    current_bulbs_ips = found_bulbs_ip
                    event.set()
                    with cond:
                        logger.info("Static bulb")
                        cond.notify()
            time.sleep(SLEEP_TIME)
        except:
            logger.exception("Got exception in static bulb")


def monitor_ping(event, cond):
    setprocname('Ping bulbs')
    import subprocess
    cmd = 'while ping -c 1 -W 2 %s >/dev/null 2>&1; do sleep 2 ; done;'
    proc_dict = {}
    for ip in BULB_IPS:
        proc_dict[ip] = subprocess.Popen((cmd % ip).split(' '))

    while True:
        for ip, proc in proc_dict.items():
            if proc.poll() is not None:
                proc.communicate()
                event.set()
                with cond:
                    logger.info("ping bulb %s", ip)
                    cond.notify()
                time.sleep(SLEEP_TIME)
                proc_dict[ip] = subprocess.Popen((cmd % ip).split(' '))


def monitor_bulb_ping(event, cond):
    """
    Continuously ping all the bulbs one by one
    """
    setprocname('Ping Bulbs')
    current_bulb_ips = sorted(list(BULB_IPS))
    all_bulb_ips = sorted(list(BULB_IPS))
    check_attempts = 3 # Number of times to double check that a bulb is truely missing
    while True:
        found_bulb_ips = []
        try:
            for ip in all_bulb_ips:
                found_bulb = int(subprocess.run(f'ping -c 1 -W 2 {ip}'.split(' '), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode)==0
                if found_bulb:
                    found_bulb_ips.append(ip)
            if found_bulb_ips != current_bulb_ips:
                new = set(found_bulb_ips) - set(current_bulb_ips)
                missing = set(current_bulb_ips) - set(found_bulb_ips)
                send_cond = False
                if new:
                    logger.info(f'Found new bulbs {new}')
                    send_cond = True
                for missing_ip in list(missing):
                    logger.info(f'Looking for missing bulb {missing_ip}')
                    for _ in range(check_attempts):
                        if int(subprocess.run(f'ping -c 1 -W 2 {missing_ip}'.split(' '), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode)==0:
                            missing -= set([missing_ip])
                            found_bulb_ips.append(missing_ip)
                            logger.info(f'Found missing bulb {missing_ip}')
                            break
                    else:
                        send_cond = True
                found_bulb_ips = sorted(found_bulb_ips)
                if found_bulb_ips == current_bulb_ips:
                    send_cond = False

                current_bulb_ips = list(found_bulb_ips)
                if send_cond:
                    event.set()
                    with cond:
                        logger.info('Ping bulb')
                        cond.notify()
            time.sleep(SLEEP_TIME)
        except Exception:
            logger.exception('Got exception in monitor_bulb_ping')
